ARG BASE_IMAGE
FROM $BASE_IMAGE

RUN pip install 'pyiceberg[s3fs,sql-postgres]' pyarrow

COPY requirements.txt ${LAMBDA_TASK_ROOT}
RUN pip install -r requirements.txt
COPY . ${LAMBDA_TASK_ROOT}

CMD [ "index.handler" ]